name: Create Tag on Dispatch

permissions:
  contents: write # needed for creating the GH release
  id-token: write

on: [repository_dispatch]
jobs:
  Create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.K3S_UPGRADE_PAT }}
        run: |
          gh release create "${{ github.event.client_payload.tag }}" --title "Release ${{ github.event.client_payload.tag }}"
